[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200
  force = false

[[headers]]
  for = "*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31556952; preload"
    Cache-Control = "public, max-age=86400"
    Content-Security-Policy = """
       default-src 'self';
       style-src 'self' https://fonts.googleapis.com;
       img-src 'self' https://static.wixstatic.com https://shoonia.wixsite.com;
       font-src 'self' https://fonts.gstatic.com;
      """

[[headers]]
  for = "*.css"

  [headers.values]
    Cache-Control = "public, max-age=31556952, immutable"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
