[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200
  force = false

[[redirects]]
  from = "https://shoonia.netlify.app/*"
  to = "https://shoonia.site/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; preload"
    Cache-Control = "public, max-age=86400"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
