[build]
  publish = "public"
  command = "DEBUG=* eleventy"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 200
  force = false

[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31556952; preload"
    Cache-Control = "public, max-age=1800"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31556952, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31556952, immutable"
