[build]
  publish = "public"
  command = "DEBUG=* eleventy"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 200
  force = false

[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31556952; preload"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31556952, immutable"

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Cache-Control = "public, max-age=31556952, immutable"
